# Generated by Django 4.1.6 on 2023-02-07 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('e8439d5b-5240-4432-8789-b23324e0acb7'), max_length=36),
        ),
    ]
