# Generated by Django 4.1.6 on 2023-02-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
